### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by theredbaron1834** [XenGi/pac#14]
Fresh install of Arch, installed pacaur and this. And pac fails to run, at least for searching.

```
pac pacaur                                    :(
1 aur/pacaur 4.7.10-1 [installed] (1008, 56.60)
  An AUR helper that minimizes user interaction
--------
8 aur/archupdate 1-2 (7, 0.24)
  A simple script to update archlinux using pacmatic and pacaur.
Traceback (most recent call last):
  File "/usr/bin/pac", line 196, in <module>
    present(entries)
  File "/usr/bin/pac", line 135, in present
    print(f'{CYELLOW2}==>{CEND} {CBOLD}Enter n\xb0 of packages to be installed (ex: 1 2 3 or 1-3){CEND}')
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 24: ordinal not in range(128)
[1]    3322 exit 1     pac pacaur

```

Running on an Acer e5-575-33bm, updated to 12gib of ddr4 and an M.2 ssd (64gib). Not sure if any other info is wanted/needed, as this was a "fresh" install.

**Comment by xnick** [comment]
What locale are you using? Is it utf-8? Beyond that, the quick and dirty fix would be to edit the file and remove the degree sign (which your system can't handle apparently) in line 135.

**Comment by theredbaron1834** [comment]
Yeah, it wasn't utf-8. Not sure why I was using en_US ISO-8859-1, but switched and now it works.

**Comment by XenGi** [comment]
Yeah this error is pretty strange. Glad you fixed it.
