### ISSUE TITLE
Selecting package 0 should exit instead of installing last package in list

### ISSUE THREAD

**Issue by KruyKaze** [XenGi/pac#19]
Thanks for creating pac.
I love the yaourt search emulation but with yaourt if I don't see a package i want in search i can just exit by entering 0 instead of a package number in the search. 
But with pac , that results in installing the last package in the list.
Thank you for looking into this.

**Comment by XenGi** [comment]
In pac you can just hit enter with an empty line to exit the search. I'll look into the error. Entering `0` should return an error or just be ignored.

**Comment by KruyKaze** [comment]
Great thanks

**Comment by XenGi** [comment]
fixed. new version is also in aur.

**Comment by XenGi** [comment]
ups.. haven't testet it

**Comment by XenGi** [comment]
now it's fixed.. I'm too tired for this.. good night.
