### ISSUE TITLE
Error Encoding Character

### ISSUE THREAD

**Issue by gatlee** [XenGi/pac#20]
```
    print(f'{CYELLOW2}==>{CEND} {CBOLD}Enter n\xb0 of packages to be installed (ex: 1 2 3 or 1-3){CEND}')
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 24: ordinal not in range(128)

```
When 'pac _searchterm_' is entered, the error message above appears.
There appears to be an error to do with the f-string formatting and the unicode character: ° when attempting to print

"Enter n° of pac..."

**Comment by xnick** [comment]
You are probably not using UTF-8. Did you just install arch and forgot to pick locales? ;)

**Comment by gatlee** [comment]
Oops my bad :sweat_smile: . Sorry about that.
Thanks for the help!
